name: Cron Reminder Masuk

on:
  schedule:
    - cron: '30 1 * * 1-6' # 08:30 WIB (Senin-Sabtu)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Send Push Notification (In)
        run: node scripts/github-cron.mjs in
